// this contains the TypeScript code for the component
// it defines severl things Angualr needs to know about the component 

import { Component } from '@angular/core'; // Gives access to basic Angular features
import { RouterOutlet } from '@angular/router';// Gives access to ANgualr router 

// @Compinent idenfies the attributes / chracteristics of the component 
@Component({
  selector: 'app-root', // where to insert the HTML generated by ANgular for the page 
  imports: [RouterOutlet],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App {
  protected title = 'myFirstAngularApp';
}
